### ISSUE TITLE
The idea for the project

### ISSUE THREAD

**Issue by itprofit** [trustmaster/SugarAsterisk#4]
If the system stores the records in Wav, you can do to listen to the asterisk on the button called user and the selected file is lost through the Playback (call_id.wav) or Background (call_id.wav).
This will allow the recording to listen to without a problem to users, even the "narrow" channel or in the absence of speakers in the workplace.

Если система хранит записи в Wav , то можно сделать, чтобы по кнопке прослушать астериск звонил пользователю и проигрывал выбранный файл через playback(call_id.wav) или  Background(call_id.wav).
Это позволит без проблем прослушивать записи пользователям, даже на "узком" канале или в отсутствии колонок на рабочем месте.

**Comment by trustmaster** [comment]
Sorry?

**Comment by itprofit** [comment]
That is in English? Or something else?

**Comment by trustmaster** [comment]
Very low priority feature :)

**Comment by itprofit** [comment]
It's just an idea. How it intersnyh developer - the developer to decide. This is a special case, but somewhere may be the only option. In addition, it requires configuring Asterisk. If this functionality appears in the system, it should be optional IMHO, that is, if you suddenly need it you can uncomment the appropriate line and adjust accordingly Asterisk. To this was not reflected in the simplicity of installing the module in the standard version.
